require_relative '../../../../node_modules/.bun/@capacitor+ios@6.2.2+bbf93636f05d5b82/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.bun/@capacitor+ios@6.2.2+bbf93636f05d5b82/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.bun/@capacitor+ios@6.2.2+bbf93636f05d5b82/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../../node_modules/.bun/@capacitor+app@6.0.3+bbf93636f05d5b82/node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../../../node_modules/.bun/@capacitor+app-launcher@6.0.4+bbf93636f05d5b82/node_modules/@capacitor/app-launcher'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/.bun/@capacitor+filesystem@6.0.4+bbf93636f05d5b82/node_modules/@capacitor/filesystem'
  pod 'CapacitorNetwork', :path => '../../../../node_modules/.bun/@capacitor+network@6.0.4+bbf93636f05d5b82/node_modules/@capacitor/network'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.bun/@capacitor+preferences@6.0.4+bbf93636f05d5b82/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../../../node_modules/.bun/@capacitor+push-notifications@6.0.5+bbf93636f05d5b82/node_modules/@capacitor/push-notifications'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
