[package]
name = "pm4-notify"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "pm4-notify"
path = "main.rs"

[target.'cfg(target_os = "macos")'.dependencies]
notify-rust = { version = "4.18", features = ["preview-macos-un"] }
objc2-foundation = { version = "0.3", features = ["NSRunLoop", "NSDate"] }

[target.'cfg(target_os = "linux")'.dependencies]
notify-rust = "4.18"
