// The entitlement key's public half: SPKI DER in base64 with its kid, one entry per key so
// a rotation can ship the next key beside the current one. A token must check against one
// of them. The private half is generated by apps/server/scripts/keygen.ts and never enters
// the tree; the brain carries the same list.

export interface EntitlementKey {
  kid: string;
  key: string;
}

export const ENTITLEMENT_KEYS: EntitlementKey[] = [
  // entitlement key 1, generated 2026-09-21
  { kid: "ent-1", key: "MCowBQYDK2VwAyEAnZFHhCyoQqIpjY8VYnkD6bipe7keku0EwKcvE+DIpwc=" },
];
