// The release key's public half: SPKI DER in base64, one entry per key so a rotation can
// ship the next key beside the current one. A release must check against one of them. The
// private half is generated by apps/installer/scripts/keygen.ts and never enters the tree.

export const RELEASE_KEYS: string[] = [
  // release key 1, generated 2026-09-19
  "MCowBQYDK2VwAyEAw0P1wlMB8iO5RUeyasIHVQyCJVG/73zwUtHZhhMXoo4=",
];
